### ISSUE TITLE
Export and import histograms

### ISSUE THREAD

**Issue by klizhentas** [codahale/hdrhistogram#1]
Hi Coda!

I have a case when I'm collecting histograms from various data sources via API and would like to merge them to get the combined histogram.

What do you think is the best way to export/import histograms for this package?

One way to do this is to add ``Export() Dump`` and ```Import(Dump) (*Histogram, error)``` functions that would operate on the following data structure:

```
type Dump struct {
    Version int
    LowestTrackableValue int64
    HighestTrackableValue int64
    SignificantFigures int64
    Counts []int64
}
```

The other approach is to make the raw iterator public, so I can implement any serialization/de-serialization logic in my app just by using iterator over counter values.

I can send a PR if you think that any of these approaches makes sense.

**Comment by codahale** [comment]
Closed by #5.
