### ISSUE TITLE
why int64 and not float64?

### ISSUE THREAD

**Issue by mranney** [codahale/hdrhistogram#13]
Do you have any plans to add support for recording float64 values as well as ints, similar to the Java version?

**Comment by StabbyCutyou** [comment]
I'd wager a guess that int64 was chosen since it maps to the time.Duration type, which would be the easiest thing to use when mapping latencies.

I wonder if you could use something like go-generate to template out the Histogram, and then build a copy for both types?

**Comment by codahale** [comment]
int64s allow you to record latencies between 0 and ~292 years using nanosecond resolution, which strikes me as sufficient. I don't have any plans to add float64 support.
