### ISSUE TITLE
class intervals and counts?

### ISSUE THREAD

**Issue by Dieterbe** [codahale/hdrhistogram#14]
Hello,
do i understand correctly that this histogram is not able to return class intervals ("buckets") and the counts thereof? (which is what i thought histograms do)
the closest i could find was the `func (*Histogram) CumulativeDistribution` but the brackets returned are delineated by the quantile they're at (e.g. how many values have been included) as opposed to value thresholds.

thanks

**Comment by codahale** [comment]
`Bracket` includes `ValueAt`, which is the ceiling of the bracket.
