### ISSUE TITLE
getBucketIndex calculates index wrong, overflows on small values

### ISSUE THREAD

**Issue by aka-rider** [codahale/hdrhistogram#25]
There is an error in the following code
`pow2Ceiling := bitLen(v | h.subBucketMask)`

Leading zero base is missing. In this case it is constant 64
`pow2Ceiling := 64 - bitLen(v | h.subBucketMask)`

**Comment by codahale** [comment]
I’d happily merge a pull request, but I don’t have time to investigate this myself.

**Comment by aka-rider** [comment]
Currently, I don't have a time to investigate it either.

**Comment by aka-rider** [comment]
Sorry, I was wrong.
Reference implementation uses clz while go uses 'bitLen'. That's where difference is.
